---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: Nkx0RltIOD1sam8wCg==
  mysql-password: bkFiM3BbKjVSNVpNCg==
  mysql-user: ZGItdXNlcm5hbWUK
  mysql-database: d3BfZGIK